import os
import subprocess
from pathlib import Path
from tkinter import messagebox


class StartMSPCMBeta:
    @staticmethod
    def start_mspcm_beta(logger=None, log_file_path=None, app_translator=None):
        registered_class_beta = "shell:AppsFolder\\Microsoft.AutoGenerated.{CDBC7B0D-6A70-5A10-4C8A-4B161DDC42A7}"
        beta_exe_path = Path(os.environ["ProgramFiles"]) / "Microsoft PC Manager" / "MSPCManager.exe"

        # --- Registered Class Methods ---
        def open_with_startfile():
            logger.info("Opening Microsoft PC Manager Public Beta via os.startfile with registered class.")
            os.startfile(registered_class_beta)

        def open_with_cmd():
            logger.info("Opening Microsoft PC Manager Public Beta via CMD with registered class.")
            subprocess.run(["cmd.exe", "/C", "start", "Microsoft PC Manager", f"{registered_class_beta}"], check=True,
                           shell=False, creationflags=subprocess.CREATE_NO_WINDOW)

        def open_with_powershell():
            logger.info("Opening Microsoft PC Manager Public Beta via Windows PowerShell with registered class.")
            subprocess.run(["powershell.exe", "-NoProfile", "-Command", f"Start-Process '{registered_class_beta}'"],
                           check=True, shell=False, creationflags=subprocess.CREATE_NO_WINDOW)
        # --- End of Registered Class Methods ---

        # --- EXE Path Methods ---
        def exe_with_startfile():
            logger.info(f"Opening Microsoft PC Manager Public Beta via os.startfile with exe path: {beta_exe_path}")
            os.startfile(str(beta_exe_path))

        def exe_with_cmd():
            logger.info(f"Opening Microsoft PC Manager Public Beta via CMD with exe path: {beta_exe_path}")
            subprocess.run(["cmd.exe", "/C", "start", "", str(beta_exe_path)], check=True,
                           shell=False, creationflags=subprocess.CREATE_NO_WINDOW)

        def exe_with_powershell():
            logger.info(f"Opening Microsoft PC Manager Public Beta via Windows PowerShell with exe path: {beta_exe_path}")
            subprocess.run(["powershell.exe", "-NoProfile", "-Command", f"Start-Process '{beta_exe_path}'"],
                           check=True, shell=False, creationflags=subprocess.CREATE_NO_WINDOW)
        # --- End of EXE Path Methods ---

        methods_registered_class = [
            open_with_startfile,
            open_with_cmd,
            open_with_powershell
        ]

        methods_exe_path = [
            exe_with_startfile,
            exe_with_cmd,
            exe_with_powershell
        ]

        # Prioritize trying registered class methods first.
        for method in methods_registered_class:
            try:
                method()
                logger.info(f"Successfully opened the Microsoft PC Manager Public Beta via {method.__name__} (registered class).")
                return
            except Exception as e:
                logger.warning(f"{method.__name__} failed to Open the Microsoft PC Manager Public Beta with Registered Class: {e}")
                continue

        # If all registered class methods fail, try the exe path methods.
        for method in methods_exe_path:
            try:
                method()
                logger.info(f"Successfully opened the Microsoft PC Manager Public Beta via {method.__name__} (exe path).")
                return
            except Exception as e:
                logger.warning(f"{method.__name__} failed to Open the Microsoft PC Manager Public Beta with EXE Path: {e}")
                continue

        logger.error("All methods failed to open the Microsoft PC Manager Public Beta.")
        messagebox.showerror(
            app_translator.translate("error"),
            app_translator.translate(f"failed_to_open_mspcm_beta").format(log_file_path=log_file_path)
        )
